module VerifyExamples.AUF.AddToAlgorithm0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import AUF exposing (..)
import Algorithm







spec0 : Test.Test
spec0 =
    Test.test "#addToAlgorithm: \n\n    addToAlgorithm\n        ( Halfway, Clockwise )\n        (Algorithm.fromTurnList [ Algorithm.Turn Algorithm.Z Algorithm.OneQuarter Algorithm.Clockwise ])\n    --> Algorithm.fromTurnList\n    -->     [ Algorithm.Turn Algorithm.U Algorithm.Halfway Algorithm.Clockwise\n    -->     , Algorithm.Turn Algorithm.Z Algorithm.OneQuarter Algorithm.Clockwise\n    -->     , Algorithm.Turn Algorithm.R Algorithm.OneQuarter Algorithm.Clockwise\n    -->     ]" <|
        \() ->
            Expect.equal
                (
                addToAlgorithm
                    ( Halfway, Clockwise )
                    (Algorithm.fromTurnList [ Algorithm.Turn Algorithm.Z Algorithm.OneQuarter Algorithm.Clockwise ])
                )
                (
                Algorithm.fromTurnList
                    [ Algorithm.Turn Algorithm.U Algorithm.Halfway Algorithm.Clockwise
                    , Algorithm.Turn Algorithm.Z Algorithm.OneQuarter Algorithm.Clockwise
                    , Algorithm.Turn Algorithm.R Algorithm.OneQuarter Algorithm.Clockwise
                    ]
                )