module VerifyExamples.Cube.Advanced.CanBeSolvedBySingleUTurn0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Cube.Advanced exposing (..)
import Algorithm







spec0 : Test.Test
spec0 =
    Test.test "#canBeSolvedBySingleUTurn: \n\n    Algorithm.fromString \"F\"\n        |> Result.map (\\alg -> canBeSolvedBySingleUTurn (applyAlgorithm alg solved))\n    --> Ok False" <|
        \() ->
            Expect.equal
                (
                Algorithm.fromString "F"
                    |> Result.map (\alg -> canBeSolvedBySingleUTurn (applyAlgorithm alg solved))
                )
                (
                Ok False
                )