module VerifyExamples.Cube.DetectAUFs0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Cube exposing (..)
import AUF
import Algorithm







spec0 : Test.Test
spec0 =
    Test.test "#detectAUFs: \n\n    detectAUFs\n        { toDetectFor = Algorithm.fromString \"R\" |> Result.withDefault Algorithm.empty\n        , toMatchTo = Algorithm.fromString \"F\" |> Result.withDefault Algorithm.empty\n        }\n    --> Nothing" <|
        \() ->
            Expect.equal
                (
                detectAUFs
                    { toDetectFor = Algorithm.fromString "R" |> Result.withDefault Algorithm.empty
                    , toMatchTo = Algorithm.fromString "F" |> Result.withDefault Algorithm.empty
                    }
                )
                (
                Nothing
                )