module VerifyExamples.Cube.DetectAUFs1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Cube exposing (..)
import AUF
import Algorithm







spec1 : Test.Test
spec1 =
    Test.test "#detectAUFs: \n\n    detectAUFs\n        { toDetectFor = Algorithm.fromString \"R\" |> Result.withDefault Algorithm.empty\n        , toMatchTo = Algorithm.fromString \"U'RU\" |> Result.withDefault Algorithm.empty\n        }\n    --> Just (AUF.CounterClockwise, AUF.Clockwise)" <|
        \() ->
            Expect.equal
                (
                detectAUFs
                    { toDetectFor = Algorithm.fromString "R" |> Result.withDefault Algorithm.empty
                    , toMatchTo = Algorithm.fromString "U'RU" |> Result.withDefault Algorithm.empty
                    }
                )
                (
                Just (AUF.CounterClockwise, AUF.Clockwise)
                )